<a href="https://colab.research.google.com/github/riyana1111/CSE-413/blob/main/assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tasks:

Use numpy to create a 3×3 matrix of random integers between 1 and 50.  
   Run the code twice
  With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.  
  Without setting a seed, allowing random values to change each time.  
  Observe and explain the differences in outputs.  (in a different cell as text)

In [5]:
import numpy as np

# Create a 3x3 matrix with a fixed seed
np.random.seed(10)
matrix_seeded = np.random.randint(1, 51, size=(3, 3))
print("Matrix with fixed seed:")
print(matrix_seeded)

# Create a 3x3 matrix without setting a seed
matrix_unseeded = np.random.randint(1, 51, size=(3, 3))
print("\nMatrix without seed:")
print(matrix_unseeded)

Matrix with fixed seed:
[[10 37 16]
 [ 1 50 29]
 [26 30 49]]

Matrix without seed:
[[30 50  9]
 [10  1 43]
 [41 37 17]]


In [ ]:
Explanation of differences:

When `np.random.seed()` is set to a specific value (like 10), the sequence of random numbers generated by NumPy is predictable. This means that every time you run the code with the same seed, you will get the exact same "random" numbers and thus the same matrix. This is crucial for reproducibility in experiments and simulations.

When `np.random.seed()` is not set, or set to `None`, the random number generator uses a different starting point (often based on system time or other factors). This results in a different sequence of random numbers each time the code is executed, leading to a different matrix in each run. This is useful when you want genuinely random results.

In the output above, the "Matrix with fixed seed" will be the same every time you run the cell. The "Matrix without seed" will likely be different each time you run its cell.